import { describe, expect, it } from 'vite-plus/test'
import { createConversationScroll } from './scroll'

describe('conversation following', () => {
  it('uses the full measured height through Markdown, footer and final timestamp growth', () => {
    const scroll = createConversationScroll()
    expect(scroll.content(800)).toBeUndefined()
    expect(scroll.viewport(600)).toBe(200)
    expect(scroll.content(980)).toBe(380)
    expect(scroll.content(1016)).toBe(416)
  })

  it('keeps following through keyboard resizing and upward native layout echoes', () => {
    const scroll = createConversationScroll()
    scroll.content(1000)
    scroll.viewport(700)
    expect(scroll.viewport(400)).toBe(600)
    scroll.scroll(600)
    expect(scroll.viewport(700)).toBe(300)
    scroll.scroll(300)
    scroll.scroll(0)
    expect(scroll.content(1120)).toBe(420)
    expect(scroll.following).toBe(true)
  })

  it('preserves a reader position through streaming completion and keyboard changes', () => {
    const scroll = createConversationScroll()
    scroll.content(1000)
    scroll.viewport(600)
    scroll.beginInteraction()
    scroll.scroll(160)
    scroll.endInteraction(160)
    expect(scroll.following).toBe(false)
    expect(scroll.content(1240)).toBeUndefined()
    expect(scroll.viewport(350)).toBeUndefined()
    expect(scroll.viewport(600)).toBeUndefined()
    scroll.scroll(640)
    expect(scroll.content(1280)).toBeUndefined()
  })

  it('does not command a scroll while the user is dragging or decelerating', () => {
    const scroll = createConversationScroll()
    scroll.content(900)
    scroll.viewport(600)
    scroll.beginInteraction()
    expect(scroll.content(940)).toBeUndefined()
    scroll.endInteraction(140)
    scroll.beginInteraction()
    scroll.scroll(80)
    expect(scroll.content(1000)).toBeUndefined()
    scroll.endInteraction(60)
    expect(scroll.content(1080)).toBeUndefined()
  })

  it('resumes when the user reaches the bottom or explicitly sends/jumps to latest', () => {
    const scroll = createConversationScroll()
    scroll.content(1000)
    scroll.viewport(600)
    scroll.beginInteraction()
    scroll.endInteraction(0)
    expect(scroll.latest()).toBe(400)
    expect(scroll.content(1200)).toBe(600)
    scroll.beginInteraction()
    scroll.scroll(0)
    scroll.scroll(590)
    scroll.endInteraction(590)
    expect(scroll.content(1280)).toBe(680)
  })

  it('does not interrupt a short upward flick before momentum begins', () => {
    const scroll = createConversationScroll()
    scroll.content(1000)
    scroll.viewport(600)
    scroll.beginInteraction()
    scroll.endDrag(390, -1, 160)
    expect(scroll.content(1040)).toBeUndefined()
    scroll.beginMomentum()
    scroll.scroll(240)
    scroll.endInteraction(160)
    expect(scroll.content(1080)).toBeUndefined()
  })

  it('ignores late momentum echoes after an explicit send or jump to latest', () => {
    const scroll = createConversationScroll()
    scroll.content(1000)
    scroll.viewport(600)
    scroll.beginInteraction()
    scroll.endDrag(200, -1, 0)
    expect(scroll.latest()).toBe(400)
    scroll.beginMomentum()
    scroll.scroll(0)
    scroll.endInteraction(0)
    expect(scroll.following).toBe(true)
    expect(scroll.content(1080)).toBe(480)
  })
})
