/** Studio adaptations of the palettes reviewed in the theme preview artifact.
 * Keep surface, accent-text and filled-action colors separate for readable contrast. */
export const studioThemeIds = [
  'dovo',
  'iris',
  'lagoon',
  'ember',
  'cobalt',
  'github',
  'tokyo',
  'catppuccin',
  'dracula',
  'vscode',
  'codex',
  'claude',
  't3code',
  'cursor',
] as const
export type StudioThemeId = (typeof studioThemeIds)[number]
export type StudioThemeMode = 'dark' | 'light'
export type StudioThemeColors = {
  background: string
  foreground: string
  sidebar: string
  card: string
  popover: string
  secondary: string
  'muted-foreground': string
  border: string
  primary: string
  selection: string
  action: string
  'action-foreground': string
  signal: string
  pink: string
  'syntax-function': string
  'syntax-keyword': string
}
export type StudioTheme = {
  name: string
  description: string
  source: string
  url?: string
  dark: StudioThemeColors
  light: StudioThemeColors
}
export const studioThemes: Record<StudioThemeId, StudioTheme> = {
  dovo: {
    name: 'Dovo',
    description: 'Graphite & blue',
    source:
      'Dark colors sampled from dovocode.com’s live CSS. Light mode is a Studio adaptation of that brand palette.',
    url: 'https://dovocode.com',
    dark: {
      background: '#080808',
      foreground: '#ededed',
      sidebar: '#0c0c0c',
      card: '#101010',
      popover: '#101010',
      secondary: '#102432',
      'muted-foreground': '#a1a1a1',
      border: '#282828',
      primary: '#7cc9ff',
      selection: '#102432',
      action: '#ededed',
      'action-foreground': '#080808',
      signal: '#bcefff',
      pink: '#7cc9ff',
      'syntax-function': '#7cc9ff',
      'syntax-keyword': '#7cc9ff',
    },
    light: {
      background: '#ffffff',
      foreground: '#151515',
      sidebar: '#f7f7f7',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#e7f3ff',
      'muted-foreground': '#666666',
      border: '#dddddd',
      primary: '#0965b5',
      selection: '#e7f3ff',
      action: '#151515',
      'action-foreground': '#ffffff',
      signal: '#006a83',
      pink: '#0965b5',
      'syntax-function': '#0965b5',
      'syntax-keyword': '#0965b5',
    },
  },
  iris: {
    name: 'Iris',
    description: 'Electric violet',
    source:
      'Original Dovo palette · informed by Dracula’s vivid accents and GitHub’s neutral surfaces.',
    dark: {
      background: '#0b0b0f',
      foreground: '#f4f3ff',
      sidebar: '#070709',
      card: '#141419',
      popover: '#141419',
      secondary: '#29203e',
      'muted-foreground': '#a7a5b8',
      border: '#2d2c38',
      primary: '#b491ff',
      selection: '#29203e',
      action: '#7c3aed',
      'action-foreground': '#ffffff',
      signal: '#5ee8ed',
      pink: '#ff83c9',
      'syntax-function': '#b491ff',
      'syntax-keyword': '#ff83c9',
    },
    light: {
      background: '#ffffff',
      foreground: '#1a1628',
      sidebar: '#f8f7fb',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#efe6ff',
      'muted-foreground': '#686176',
      border: '#dedbe7',
      primary: '#6d28d9',
      selection: '#efe6ff',
      action: '#6d28d9',
      'action-foreground': '#ffffff',
      signal: '#007b83',
      pink: '#bb176f',
      'syntax-function': '#6d28d9',
      'syntax-keyword': '#bb176f',
    },
  },
  lagoon: {
    name: 'Lagoon',
    description: 'Mint & cyan',
    source: 'Original Dovo palette · neutral surfaces with a mint / cyan accent family.',
    dark: {
      background: '#090d0e',
      foreground: '#effbfa',
      sidebar: '#060909',
      card: '#12191a',
      popover: '#12191a',
      secondary: '#103930',
      'muted-foreground': '#9cabad',
      border: '#293537',
      primary: '#2de2c3',
      selection: '#103930',
      action: '#2de2c3',
      'action-foreground': '#002b25',
      signal: '#62d9ff',
      pink: '#c69aff',
      'syntax-function': '#2de2c3',
      'syntax-keyword': '#c69aff',
    },
    light: {
      background: '#ffffff',
      foreground: '#102a28',
      sidebar: '#f6faf9',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#dcf8ee',
      'muted-foreground': '#5c716e',
      border: '#d5e3df',
      primary: '#007765',
      selection: '#dcf8ee',
      action: '#007765',
      'action-foreground': '#ffffff',
      signal: '#006caa',
      pink: '#823bcc',
      'syntax-function': '#007765',
      'syntax-keyword': '#823bcc',
    },
  },
  ember: {
    name: 'Ember',
    description: 'Tangerine & amber',
    source: 'Original Dovo palette · brighter orange controls, minimal warm surface tint.',
    dark: {
      background: '#0e0b09',
      foreground: '#fff5ee',
      sidebar: '#090705',
      card: '#191410',
      popover: '#191410',
      secondary: '#3b2515',
      'muted-foreground': '#b6a69c',
      border: '#393029',
      primary: '#ff9a44',
      selection: '#3b2515',
      action: '#ff8a2b',
      'action-foreground': '#301500',
      signal: '#ffd36a',
      pink: '#bf9dff',
      'syntax-function': '#ff9a44',
      'syntax-keyword': '#bf9dff',
    },
    light: {
      background: '#ffffff',
      foreground: '#2f1e13',
      sidebar: '#fdf9f5',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#fff0df',
      'muted-foreground': '#7a6658',
      border: '#e8ded5',
      primary: '#b24700',
      selection: '#fff0df',
      action: '#b24700',
      'action-foreground': '#ffffff',
      signal: '#956100',
      pink: '#7338bc',
      'syntax-function': '#b24700',
      'syntax-keyword': '#7338bc',
    },
  },
  cobalt: {
    name: 'Cobalt',
    description: 'Electric blue',
    source: 'Original Dovo palette · informed by Tokyo Night’s blue / cyan color family.',
    dark: {
      background: '#090c12',
      foreground: '#eef4ff',
      sidebar: '#06080c',
      card: '#121923',
      popover: '#121923',
      secondary: '#172b49',
      'muted-foreground': '#9eaac0',
      border: '#293448',
      primary: '#70a7ff',
      selection: '#172b49',
      action: '#2563eb',
      'action-foreground': '#ffffff',
      signal: '#5fe7ff',
      pink: '#c394ff',
      'syntax-function': '#70a7ff',
      'syntax-keyword': '#c394ff',
    },
    light: {
      background: '#ffffff',
      foreground: '#14243e',
      sidebar: '#f7f9fd',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#e7f0ff',
      'muted-foreground': '#586a84',
      border: '#d8e1ed',
      primary: '#145bd7',
      selection: '#e7f0ff',
      action: '#145bd7',
      'action-foreground': '#ffffff',
      signal: '#00788e',
      pink: '#7d36c5',
      'syntax-function': '#145bd7',
      'syntax-keyword': '#7d36c5',
    },
  },
  github: {
    name: 'GitHub',
    description: 'Blue & green',
    source: 'Inspired by GitHub / Primer. Studio-specific mapping; not an exact GitHub theme.',
    url: 'https://primer-docs-preview.github.com/product/getting-started/foundations/color-usage/',
    dark: {
      background: '#0d1117',
      foreground: '#f0f6fc',
      sidebar: '#010409',
      card: '#161b22',
      popover: '#161b22',
      secondary: '#172e4b',
      'muted-foreground': '#9da7b3',
      border: '#30363d',
      primary: '#58a6ff',
      selection: '#172e4b',
      action: '#238636',
      'action-foreground': '#ffffff',
      signal: '#79c0ff',
      pink: '#ff7b72',
      'syntax-function': '#58a6ff',
      'syntax-keyword': '#ff7b72',
    },
    light: {
      background: '#ffffff',
      foreground: '#1f2328',
      sidebar: '#f6f8fa',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#ddf4ff',
      'muted-foreground': '#59636e',
      border: '#d1d9e0',
      primary: '#0969da',
      selection: '#ddf4ff',
      action: '#1a7f37',
      'action-foreground': '#ffffff',
      signal: '#0550ae',
      pink: '#a40e26',
      'syntax-function': '#0969da',
      'syntax-keyword': '#a40e26',
    },
  },
  tokyo: {
    name: 'Tokyo Night',
    description: 'Midnight & cyan',
    source: 'Adapted from Tokyo Night. Surfaces darkened / lightened for this preview.',
    url: 'https://github.com/tokyo-night/tokyo-night-vscode-theme',
    dark: {
      background: '#0c0d14',
      foreground: '#c0caf5',
      sidebar: '#080910',
      card: '#151620',
      popover: '#151620',
      secondary: '#202a47',
      'muted-foreground': '#9aa6d5',
      border: '#30334c',
      primary: '#7aa2f7',
      selection: '#202a47',
      action: '#7aa2f7',
      'action-foreground': '#11172a',
      signal: '#7dcfff',
      pink: '#bb9af7',
      'syntax-function': '#7aa2f7',
      'syntax-keyword': '#bb9af7',
    },
    light: {
      background: '#ffffff',
      foreground: '#343b58',
      sidebar: '#f6f7fb',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#e6edff',
      'muted-foreground': '#626984',
      border: '#d5d9e8',
      primary: '#2e5cba',
      selection: '#e6edff',
      action: '#2e5cba',
      'action-foreground': '#ffffff',
      signal: '#006b83',
      pink: '#7843b7',
      'syntax-function': '#2e5cba',
      'syntax-keyword': '#7843b7',
    },
  },
  catppuccin: {
    name: 'Catppuccin',
    description: 'Lavender & peach',
    source:
      'Adapted from Catppuccin Mocha / Latte. Surfaces deepened / whitened; text adjusted for contrast.',
    url: 'https://catppuccin.com/palette/',
    dark: {
      background: '#11111b',
      foreground: '#cdd6f4',
      sidebar: '#08080f',
      card: '#181825',
      popover: '#181825',
      secondary: '#302240',
      'muted-foreground': '#a6adc8',
      border: '#313244',
      primary: '#cba6f7',
      selection: '#302240',
      action: '#cba6f7',
      'action-foreground': '#241335',
      signal: '#94e2d5',
      pink: '#fab387',
      'syntax-function': '#cba6f7',
      'syntax-keyword': '#fab387',
    },
    light: {
      background: '#ffffff',
      foreground: '#4c4f69',
      sidebar: '#f8f9fc',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#f5edff',
      'muted-foreground': '#666980',
      border: '#dce0e8',
      primary: '#8839ef',
      selection: '#f5edff',
      action: '#8839ef',
      'action-foreground': '#ffffff',
      signal: '#00787d',
      pink: '#b74900',
      'syntax-function': '#8839ef',
      'syntax-keyword': '#b74900',
    },
  },
  dracula: {
    name: 'Dracula',
    description: 'Purple & pink',
    source:
      'Adapted from Dracula / Alucard. Near-black and near-white surfaces replace the originals.',
    url: 'https://draculatheme.com/spec',
    dark: {
      background: '#0f1016',
      foreground: '#f8f8f2',
      sidebar: '#090a0f',
      card: '#191a23',
      popover: '#191a23',
      secondary: '#302341',
      'muted-foreground': '#a4add0',
      border: '#343746',
      primary: '#bd93f9',
      selection: '#302341',
      action: '#bd93f9',
      'action-foreground': '#25143e',
      signal: '#8be9fd',
      pink: '#ff79c6',
      'syntax-function': '#bd93f9',
      'syntax-keyword': '#ff79c6',
    },
    light: {
      background: '#ffffff',
      foreground: '#1f1f1f',
      sidebar: '#fbfaf6',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#eee8ff',
      'muted-foreground': '#6c664b',
      border: '#e0ddcf',
      primary: '#644ac9',
      selection: '#eee8ff',
      action: '#644ac9',
      'action-foreground': '#ffffff',
      signal: '#036a96',
      pink: '#a3144d',
      'syntax-function': '#644ac9',
      'syntax-keyword': '#a3144d',
    },
  },
  vscode: {
    name: 'VS Code',
    description: 'Dark & Light Modern',
    source:
      'Based on VS Code Dark Modern / Light Modern, with inherited Dark+ / Light+ syntax colors. Studio-specific component mapping.',
    url: 'https://github.com/microsoft/vscode/tree/main/extensions/theme-defaults/themes',
    dark: {
      background: '#1f1f1f',
      foreground: '#cccccc',
      sidebar: '#181818',
      card: '#202020',
      popover: '#202020',
      secondary: '#202d3a',
      'muted-foreground': '#9d9d9d',
      border: '#2b2b2b',
      primary: '#4daafc',
      selection: '#202d3a',
      action: '#0078d4',
      'action-foreground': '#ffffff',
      signal: '#ce9178',
      pink: '#569cd6',
      'syntax-function': '#dcdcaa',
      'syntax-keyword': '#569cd6',
    },
    light: {
      background: '#ffffff',
      foreground: '#3b3b3b',
      sidebar: '#f8f8f8',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#e8e8e8',
      'muted-foreground': '#616161',
      border: '#e5e5e5',
      primary: '#005fb8',
      selection: '#e8e8e8',
      action: '#005fb8',
      'action-foreground': '#ffffff',
      signal: '#a31515',
      pink: '#0000ff',
      'syntax-function': '#795e26',
      'syntax-keyword': '#0000ff',
    },
  },
  codex: {
    name: 'Codex',
    description: 'Neutral & monochrome',
    source:
      'Based on color tokens in the installed ChatGPT / Codex app. Surfaces mapped to Studio; syntax and selection tones adapted.',
    url: 'https://learn.chatgpt.com/docs/reference/settings',
    dark: {
      background: '#181818',
      foreground: '#dfdfdf',
      sidebar: '#101010',
      card: '#212121',
      popover: '#212121',
      secondary: '#203047',
      'muted-foreground': '#afafaf',
      border: '#303030',
      primary: '#a4cdfb',
      selection: '#203047',
      action: '#ffffff',
      'action-foreground': '#181818',
      signal: '#66d492',
      pink: '#c4a4fa',
      'syntax-function': '#a4cdfb',
      'syntax-keyword': '#c4a4fa',
    },
    light: {
      background: '#ffffff',
      foreground: '#1a1c1f',
      sidebar: '#f9f9f9',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#e8f3fe',
      'muted-foreground': '#5d5d5d',
      border: '#dedede',
      primary: '#2c67c5',
      selection: '#e8f3fe',
      action: '#1a1c1f',
      'action-foreground': '#ffffff',
      signal: '#007b35',
      pink: '#7644b5',
      'syntax-function': '#2c67c5',
      'syntax-keyword': '#7644b5',
    },
  },
  claude: {
    name: 'Claude',
    description: 'Warm & terracotta',
    source:
      'Based on the installed Claude app’s bundled warm-neutral and terracotta tokens. Accent text and controls adjusted for contrast.',
    url: 'https://claude.com',
    dark: {
      background: '#262624',
      foreground: '#faf9f5',
      sidebar: '#1f1e1d',
      card: '#30302e',
      popover: '#30302e',
      secondary: '#3e2b24',
      'muted-foreground': '#bdbbb3',
      border: '#474640',
      primary: '#e6956b',
      selection: '#3e2b24',
      action: '#d97757',
      'action-foreground': '#141413',
      signal: '#74abe2',
      pink: '#cbb2ef',
      'syntax-function': '#e6956b',
      'syntax-keyword': '#cbb2ef',
    },
    light: {
      background: '#faf9f5',
      foreground: '#141413',
      sidebar: '#f5f4ed',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#fae9e1',
      'muted-foreground': '#6c6b65',
      border: '#dfddd5',
      primary: '#ad482b',
      selection: '#fae9e1',
      action: '#ad482b',
      'action-foreground': '#ffffff',
      signal: '#1b67b2',
      pink: '#6843a3',
      'syntax-function': '#ad482b',
      'syntax-keyword': '#6843a3',
    },
  },
  t3code: {
    name: 'T3 Code',
    description: 'Black & bright blue',
    source:
      'Mapped from T3 Code’s published default dark / light theme tokens. Blue text uses its readable update color; syntax adapted for the preview.',
    url: 'https://github.com/pingdotgg/t3code/blob/main/packages/shared/src/themePalettes.ts',
    dark: {
      background: '#0a0a0a',
      foreground: '#f5f5f5',
      sidebar: '#000000',
      card: '#111111',
      popover: '#111111',
      secondary: '#111111',
      'muted-foreground': '#818181',
      border: '#191919',
      primary: '#51a2ff',
      selection: '#111111',
      action: '#346bf1',
      'action-foreground': '#ffffff',
      signal: '#72ddb5',
      pink: '#bda4ff',
      'syntax-function': '#51a2ff',
      'syntax-keyword': '#bda4ff',
    },
    light: {
      background: '#fcfcfc',
      foreground: '#27272a',
      sidebar: '#fafafa',
      card: '#ffffff',
      popover: '#ffffff',
      secondary: '#ffffff',
      'muted-foreground': '#71717b',
      border: '#e4e4e7',
      primary: '#1b4ed8',
      selection: '#ffffff',
      action: '#1b4ed8',
      'action-foreground': '#ffffff',
      signal: '#007652',
      pink: '#7543ba',
      'syntax-function': '#1b4ed8',
      'syntax-keyword': '#7543ba',
    },
  },
  cursor: {
    name: 'Cursor',
    description: 'Graphite & slate blue',
    source:
      'Adapted from the Cursor Themes for VS Code community reproduction. Alpha borders flattened; muted text adjusted for Studio.',
    url: 'https://github.com/evanlong-me/cursor-themes-vscode',
    dark: {
      background: '#181818',
      foreground: '#f0f0f0',
      sidebar: '#141414',
      card: '#202020',
      popover: '#202020',
      secondary: '#262c35',
      'muted-foreground': '#a0a0a0',
      border: '#303030',
      primary: '#81a1c1',
      selection: '#262c35',
      action: '#81a1c1',
      'action-foreground': '#191c22',
      signal: '#e394dc',
      pink: '#82d2ce',
      'syntax-function': '#efb080',
      'syntax-keyword': '#82d2ce',
    },
    light: {
      background: '#fcfcfc',
      foreground: '#141414',
      sidebar: '#f3f3f3',
      card: '#fcfcfc',
      popover: '#fcfcfc',
      secondary: '#e9edf1',
      'muted-foreground': '#626262',
      border: '#d0d0d0',
      primary: '#0064b0',
      selection: '#e9edf1',
      action: '#2778c1',
      'action-foreground': '#fcfcfc',
      signal: '#7565cc',
      pink: '#a30034',
      'syntax-function': '#cd4500',
      'syntax-keyword': '#a30034',
    },
  },
}

/** A Shiki-compatible theme used by both markdown and file/diff viewers. */
function createSyntaxTheme(id: StudioThemeId, mode: StudioThemeMode) {
  const colors = studioThemes[id][mode]
  return {
    name: `dovo-${id}-${mode}`,
    type: mode,
    fg: colors.foreground,
    bg: colors.card,
    colors: {
      'editor.foreground': colors.foreground,
      'editor.background': colors.card,
      'editor.selectionBackground': colors.selection,
      'editorLineNumber.foreground': colors['muted-foreground'],
      'editorGutter.addedBackground': mode === 'dark' ? '#4deb8c' : '#14753c',
      'editorGutter.deletedBackground': mode === 'dark' ? '#ff7e97' : '#ba2549',
    },
    tokenColors: [
      {
        scope: ['comment', 'punctuation.definition.comment'],
        settings: { foreground: colors['muted-foreground'] },
      },
      { scope: ['keyword', 'storage'], settings: { foreground: colors['syntax-keyword'] } },
      { scope: ['string', 'constant.other.symbol'], settings: { foreground: colors.signal } },
      { scope: ['constant.numeric', 'constant.language'], settings: { foreground: colors.pink } },
      {
        scope: ['entity.name.function', 'support.function'],
        settings: { foreground: colors['syntax-function'] },
      },
      {
        scope: ['entity.name.type', 'entity.name.class', 'support.type'],
        settings: { foreground: colors.primary },
      },
    ],
  }
}
const syntaxThemes = new Map(
  studioThemeIds.map((id) => [
    id,
    {
      light: createSyntaxTheme(id, 'light'),
      dark: createSyntaxTheme(id, 'dark'),
    },
  ]),
)
export function studioSyntaxTheme(id: StudioThemeId, mode: StudioThemeMode) {
  // Every validated palette ID is initialized above.
  const themes = syntaxThemes.get(id)
  if (!themes) throw new Error(`Unknown Studio theme: ${id}`)
  return themes[mode]
}
