import {
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  Check,
  ChevronLeft,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  Copy,
  Ellipsis,
  Folder,
  FileCode2,
  Files,
  CodeXml,
  Eye,
  FolderGit2,
  GitBranch,
  GitPullRequest,
  Globe,
  House,
  History,
  Keyboard,
  Layers,
  ListFilter,
  Maximize2,
  Mic,
  Minimize2,
  Monitor,
  Paperclip,
  Pencil,
  Plus,
  RotateCw,
  Search,
  Save,
  Share2,
  Settings,
  Square,
  SquareTerminal,
  Star,
  Trash2,
  Users,
  Waves,
  X,
  Car,
  MessageCircle,
  ListPlus,
  MessagesSquare,
  CircleDot,
  Workflow,
  Info,
  MailOpen,
  Mail,
  Pin,
  PinOff,
  AlarmClock,
  Archive,
  Undo2,
  ExternalLink,
  MessageCirclePlus,
  type LucideIcon,
} from 'lucide-react-native'
import { colors } from '../theme'
const icons = {
  agents: Users,
  expand: Maximize2,
  collapse: Minimize2,
  edit: Pencil,
  add: Plus,
  web: Globe,
  chat: MessageCircle,
  device: Monitor,
  terminal: SquareTerminal,
  changes: GitBranch,
  refresh: RotateCw,
  star: Star,
  moveUp: ArrowUp,
  moveDown: ArrowDown,
  trash: Trash2,
  filters: ListFilter,
  search: Search,
  tasks: MessagesSquare,
  issues: CircleDot,
  pulls: GitPullRequest,
  stack: Layers,
  jobs: Workflow,
  settings: Settings,
  send: ArrowUp,
  queue: ListPlus,
  steer: ArrowUpRight,
  stop: Square,
  close: X,
  back: ChevronLeft,
  down: ChevronDown,
  next: ChevronRight,
  check: Check,
  copy: Copy,
  error: CircleAlert,
  attach: Paperclip,
  keyboard: Keyboard,
  folder: Folder,
  artifact: FileCode2,
  artifactList: Files,
  code: CodeXml,
  preview: Eye,
  history: History,
  save: Save,
  share: Share2,
  projects: FolderGit2,
  home: House,
  microphone: Mic,
  waveform: Waves,
  car: Car,
  more: Ellipsis,
  info: Info,
  read: MailOpen,
  unread: Mail,
  pin: Pin,
  unpin: PinOff,
  snooze: AlarmClock,
  archive: Archive,
  reopen: Undo2,
  external: ExternalLink,
  newChat: MessageCirclePlus,
} satisfies Record<string, LucideIcon>
export type IconName = keyof typeof icons
export function Icon({
  name,
  size = 20,
  color = colors.text,
}: {
  name: IconName
  size?: number
  color?: string
}) {
  const Glyph = icons[name]
  return <Glyph size={size} color={color} strokeWidth={2} accessible={false} />
}
