import {
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  Check,
  ChevronLeft,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  Copy,
  Ellipsis,
  Folder,
  GitBranch,
  GitPullRequest,
  Globe,
  House,
  Keyboard,
  Layers,
  ListFilter,
  ListTodo,
  Maximize2,
  Mic,
  Minimize2,
  Monitor,
  Paperclip,
  Pencil,
  Plus,
  RotateCw,
  Search,
  Settings,
  Square,
  SquareTerminal,
  Star,
  Trash2,
  Users,
  Waves,
  X,
  Car,
  MessageCircle,
  ListPlus,
  type LucideIcon,
} from 'lucide-react-native'
import { colors } from '../theme'
/** Native toolbar and tab symbols; custom React Native controls use Lucide below. */
export const symbols = {
  agents: ['person.2', '♙', 'group'],
  expand: ['arrow.up.left.and.arrow.down.right', '⤢', 'open_in_full'],
  collapse: ['arrow.down.right.and.arrow.up.left', '⤡', 'close_fullscreen'],
  edit: ['pencil', '✎', 'edit'],
  add: ['plus', '+', 'add'],
  web: ['globe', '◎', 'language'],
  chat: ['bubble.left', '▤', 'chat_bubble'],
  device: ['desktopcomputer', '▣', 'computer'],
  terminal: ['terminal', '⌘', 'terminal'],
  changes: ['arrow.triangle.branch', '⑂', 'difference'],
  refresh: ['arrow.clockwise', '↻', 'refresh'],
  star: ['star', '★', 'star'],
  moveUp: ['arrow.up', '↑', 'arrow_upward'],
  moveDown: ['arrow.down', '↓', 'arrow_downward'],
  trash: ['trash', '×', 'delete'],
  filters: ['line.3.horizontal.decrease', '☷', 'filter_list'],
  search: ['magnifyingglass', '⌕', 'search'],
  tasks: ['checklist', '☑', 'checklist'],
  pulls: ['arrow.triangle.pull', '⑂', 'merge'],
  stack: ['square.stack.3d.up', '▱', 'layers'],
  jobs: ['square.stack.3d.up', '▱', 'layers'],
  settings: ['gearshape', '⚙', 'settings'],
  send: ['arrow.up', '↑', 'arrow_upward'],
  queue: ['text.badge.plus', '☰+', 'playlist_add'],
  steer: ['arrow.turn.up.right', '↱', 'turn_right'],
  stop: ['stop.fill', '■', 'stop'],
  close: ['xmark', '×', 'close'],
  back: ['chevron.left', '‹', 'arrow_back'],
  down: ['chevron.down', '⌄', 'keyboard_arrow_down'],
  next: ['chevron.right', '›', 'chevron_right'],
  check: ['checkmark', '✓', 'check'],
  copy: ['doc.on.doc', '⧉', 'content_copy'],
  error: ['exclamationmark.circle', '!', 'error'],
  attach: ['paperclip', '＋', 'attach_file'],
  keyboard: ['keyboard.chevron.compact.down', '⌄', 'keyboard_hide'],
  folder: ['folder', '▱', 'folder'],
  home: ['house', '⌂', 'home'],
  microphone: ['mic', '●', 'mic'],
  waveform: ['waveform', '≋', 'graphic_eq'],
  car: ['car', '⛟', 'directions_car'],
  more: ['ellipsis', '⋯', 'more_vert'],
} as const
export type IconName = keyof typeof symbols
const icons = {
  agents: Users,
  expand: Maximize2,
  collapse: Minimize2,
  edit: Pencil,
  add: Plus,
  web: Globe,
  chat: MessageCircle,
  device: Monitor,
  terminal: SquareTerminal,
  changes: GitBranch,
  refresh: RotateCw,
  star: Star,
  moveUp: ArrowUp,
  moveDown: ArrowDown,
  trash: Trash2,
  filters: ListFilter,
  search: Search,
  tasks: ListTodo,
  pulls: GitPullRequest,
  stack: Layers,
  jobs: Layers,
  settings: Settings,
  send: ArrowUp,
  queue: ListPlus,
  steer: ArrowUpRight,
  stop: Square,
  close: X,
  back: ChevronLeft,
  down: ChevronDown,
  next: ChevronRight,
  check: Check,
  copy: Copy,
  error: CircleAlert,
  attach: Paperclip,
  keyboard: Keyboard,
  folder: Folder,
  home: House,
  microphone: Mic,
  waveform: Waves,
  car: Car,
  more: Ellipsis,
} satisfies Record<IconName, LucideIcon>
export function Icon({
  name,
  size = 20,
  color = colors.text,
}: {
  name: IconName
  size?: number
  color?: string
}) {
  const Glyph = icons[name]
  return <Glyph size={size} color={color} strokeWidth={2} accessible={false} />
}
