import { defineStudioExtension } from '@dovo/studio-core'

/** App-level settings shipped with the shell on desktop and web. */
export const appSettingsExtension = defineStudioExtension(
  { id: 'dovo.app', name: 'App', version: '0.1.0' },
  [
    {
      id: 'general',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'General',
      icon: 'runtime',
      order: 0.1,
      settingsSection: 'app',
      keywords:
        'organization startup launch open time clock sort order grouping projects confirmation archive stop cancel battery background',
      load: () => import('./app-settings/general'),
    },
    {
      id: 'conversation-settings',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'Conversation',
      icon: 'runtime',
      order: 0.3,
      settingsSection: 'app',
      keywords:
        'send enter composer conversation chat follow up queue steer streaming paragraphs markdown preview collapse tools skills slash menu',
      load: () => import('./app-settings/conversation'),
    },
    {
      id: 'updates-settings',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'Updates & about',
      icon: 'runtime',
      order: 0.7,
      settingsSection: 'app',
      keywords: 'updates version release channel stable nightly licenses notices about',
      load: () => import('./app-settings/about'),
    },
    {
      id: 'browser-settings',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'Browser',
      icon: 'runtime',
      order: 0.6,
      settingsSection: 'app',
      keywords: 'browser local remote tabs profile profiles cookies logins viewport preview',
      load: () => import('./app-settings/browser'),
    },
    {
      id: 'notifications',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'Notifications',
      icon: 'runtime',
      order: 0.4,
      settingsSection: 'app',
      keywords:
        'notifications notify alert sound background input approval question finished failed automation job run',
      load: () => import('./app-settings/notifications'),
    },
    {
      id: 'appearance',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'Appearance',
      icon: 'runtime',
      order: 0.2,
      settingsSection: 'app',
      keywords: 'theme dark light system mode color text size font zoom motion animation reduce',
      load: () => import('./app-settings/appearance'),
    },
    {
      id: 'diffs',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'Review & diffs',
      icon: 'runtime',
      order: 3.2,
      settingsSection: 'coding',
      keywords:
        'diff review split unified wrap scroll line numbers word character highlight changes',
      load: () => import('./app-settings/diffs'),
    },
    {
      id: 'pull-request-settings',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'Pull requests',
      icon: 'runtime',
      order: 3.1,
      settingsSection: 'coding',
      keywords: 'pull request pr draft merge squash rebase method create',
      load: () => import('./app-settings/pull-requests'),
    },
    {
      id: 'usage',
      navigationGroup: 'settings',
      settingsScope: 'computer',
      title: 'Usage & limits',
      icon: 'runtime',
      order: 2.4,
      settingsSection: 'agents',
      keywords:
        'usage limits quota allowance reset codex claude tokens time turns models statistics week month',
      load: () => import('./app-settings/usage'),
    },
    {
      id: 'shortcuts',
      navigationGroup: 'settings',
      settingsScope: 'device',
      title: 'Keyboard shortcuts',
      icon: 'runtime',
      order: 0.5,
      settingsSection: 'app',
      keywords: 'keyboard shortcuts hotkeys keys bindings command palette',
      load: () => import('./app-settings/shortcuts'),
    },
  ],
)
