import { StyleSheet } from 'react-native'
export const colors = {
  background: '#000000',
  surface: '#171719',
  elevated: '#242426',
  border: '#ffffff14',
  text: '#f2f2f3',
  muted: '#929298',
  accent: '#6baeff',
  error: '#ff9898',
  success: '#8ad5b0',
  warning: '#e7c681',
}
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, gap: 12 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 14,
    gap: 10,
  },
  title: { color: colors.text, fontSize: 20, fontWeight: '700', letterSpacing: -0.4 },
  largeTitle: { color: colors.text, fontSize: 34, fontWeight: '700', letterSpacing: 0.3 },
  separator: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border },
  sheetFooter: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    gap: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  empty: { paddingHorizontal: 24, paddingVertical: 48, alignItems: 'center', gap: 10 },
  listItem: {
    paddingVertical: 12,
    gap: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  text: { color: colors.text, fontSize: 17, lineHeight: 24 },
  chatText: { color: colors.text, fontSize: 15, lineHeight: 22 },
  muted: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  error: { color: colors.error, fontSize: 13, lineHeight: 18 },
  input: {
    color: colors.text,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    fontSize: 17,
    minHeight: 44,
    backgroundColor: colors.surface,
  },
})
