import { StyleSheet } from 'react-native'
export const colors = {
  background: '#0a0a0a',
  surface: '#111111',
  elevated: '#1c1c1c',
  border: '#242424',
  text: '#e8e9ed',
  muted: '#a0a1a8',
  accent: '#a5b4fc',
  onAccent: '#111525',
  error: '#ff9898',
  success: '#8ad5b0',
  warning: '#e7c681',
}
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, gap: 12 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    gap: 8,
  },
  title: { color: colors.text, fontSize: 19, fontWeight: '700', letterSpacing: -0.3 },
  largeTitle: { color: colors.text, fontSize: 30, fontWeight: '700', letterSpacing: -0.6 },
  separator: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border },
  sheetFooter: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  empty: { paddingHorizontal: 20, paddingVertical: 32, alignItems: 'center', gap: 8 },
  listItem: {
    paddingVertical: 8,
    gap: 3,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  text: { color: colors.text, fontSize: 16, lineHeight: 22 },
  chatText: { color: colors.text, fontSize: 15, lineHeight: 22 },
  muted: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  error: { color: colors.error, fontSize: 13, lineHeight: 18 },
  input: {
    color: colors.text,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 16,
    minHeight: 44,
    backgroundColor: colors.surface,
  },
})
